# Generated by Django 2.0.2 on 2018-02-08 12:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 8, 12, 21, 53, 911741, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseuser',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
