# Generated by Django 2.0.2 on 2018-02-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customauth', '0002_auto_20180208_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseuser',
            options={'get_latest_by': 'created_at'},
        ),
    ]
