# Generated by Django 2.0.2 on 2018-02-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=300)),
                ('children', models.ManyToManyField(related_name='_category_children_+', to='categories.Category')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'created_at',
            },
        ),
    ]
