# Generated by Django 2.0.2 on 2018-02-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(editable=False)),
                ('name', models.CharField(blank=True, max_length=300)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(default='items/photos/default.png', upload_to='')),
                ('items', models.ManyToManyField(to='categories.Category')),
            ],
            options={
                'abstract': False,
                'get_latest_by': 'created_at',
            },
        ),
    ]
