# Generated by Django 2.0.2 on 2018-02-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
