# Generated by Django 2.0.2 on 2018-02-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_auto_20180208_1040'),
        ('items', '0002_auto_20180208_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='items',
        ),
        migrations.AddField(
            model_name='item',
            name='categories',
            field=models.ManyToManyField(related_name='items', to='categories.Category'),
        ),
    ]
